### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by yekeen-nasir**
I modified the usefulness resources,25/8 support, safe and reliable fixes

### CODE REVIEW

**Comment by yekeen-nasir** [comment]
lets move

**Comment by idk-wym** [comment]
you dey para o 😂

**Comment by cxdemxn** [comment]
> lets move

you dey para o 😂

**Comment by yekeen-nasir** [comment]
ohh
u online......thats good
buh.....i think i still can't merge things together without ur permission

**Comment by cxdemxn** [comment]
idk why, you should be able to atp
you have accepted to being a collaborator yeah?

**Comment by cxdemxn** [comment]
i see that you have, you should be able to. 
unless there's some access setting i'm missing

**Comment by yekeen-nasir** [comment]
alrght
so what we working on now?

**Comment by cxdemxn** [comment]
i created two new issues, check them out. 
we can talk there too

**Comment by yekeen-nasir** [comment]
honestly......i can be on this system for a day

**Comment by cxdemxn** [comment]
life outside your system is an illusion 😵‍💫

**Comment by yekeen-nasir** [comment]
lol......nahhhhhh

**Comment by yekeen-nasir** [comment]
changed the name of the clients already.....down to u

**Comment by cxdemxn** [comment]
okay!!
please leave messages for specific changes under its respective issue
it helps for a more detailed history

**Pull request merged**
